plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ludoarena.online'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ashish.ludovibe.stable20260910'
        minSdk 21
        targetSdk 35
        versionCode 4
        versionName '3.0.0'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
